---
tags: [maven]
projects: []
---
:spring_boot_version: 1.5.6.RELEASE
:jdk: http://www.oracle.com/technetwork/java/javase/downloads/index.html
:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-maven
本指南引导您通过使用Maven构建一个简单的java项目。

== 你将构建什么

你会创建一个提供了当天时间的应用程序，然后用Maven构建它。

== 你需要什么

 - 大概15分钟
 - 一个你喜欢的文本编辑器或IDE
 - {jdk}[JDK 6] 或更新的版本


include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/how_to_complete_this_guide.adoc[]

[[scratch]]
== 建立项目

首先你需要建立一个用来maven构建的Java项目。为了把焦点集中在Maven，我们现在使项目尽可能简单。

include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/create_directory_structure_hello.adoc[]


在 `src/main/java/hello` 目录下, 你能创建一个你想要的Java类。为了保持与本指南其余部分的一致性，创建这两个类: `HelloWorld.java` 和 `Greeter.java`.

`src/main/java/hello/HelloWorld.java`
[source,java]
----
include::initial/src/main/java/hello/HelloWorld.java[]
----

`src/main/java/hello/Greeter.java`
[source,java]
----
include::initial/src/main/java/hello/Greeter.java[]
----


[[initial]]

现在，你已经为Maven构建准备了一个项目，下一步就是安装Maven。

可以在http://maven.apache.org/download.cgi下载Maven的zip文件。只有二进制文件是必需的，所以寻找 apache-maven-_{version}_-bin.zip 或A apache-maven-_{version}_-bin.tar.gz 的链接。

一旦你已经下载压缩文件，解压缩到您的计算机。然后加入 _bin_ 文件夹到你的路径。

测试Maven的安装，在命令行运行 `mvn` ：

----
mvn -v
----

如果一切顺利，你应该得到一些关于Maven的安装信息。它看起来类似于（尽管可能略有不同）以下:

....
Apache Maven 3.0.5 (r01de14724cdef164cd33c7c8c2fe155faf9602da; 2013-02-19 07:51:28-0600)
Maven home: /usr/share/maven
Java version: 1.7.0_09, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_09.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.8.3", arch: "x86_64", family: "mac"
....

祝贺你!你现在已经装好Maven。

== 定义一个简单的Maven构建
Now that Maven is installed, you need to create a Maven project definition. Maven projects are defined with an XML file named _pom.xml_. Among other things, this file gives the project's name, version, and dependencies that it has on external libraries.

Create a file named _pom.xml_ at the root of the project and give it the following contents:

`pom.xml`
[source,XML]
----
include::initial/pom.xml[]
----

With the exception of the optional `<packaging>` element, this is the simplest possible _pom.xml_ file necessary to build a Java project. It includes the following details of the project configuration:

* `<modelVersion>`. POM model version (always 4.0.0).
* `<groupId>`. Group or organization that the project belongs to. Often expressed as an inverted domain name.
* `<artifactId>`. Name to be given to the project's library artifact (for example, the name of its JAR or WAR file).
* `<version>`. Version of the project that is being built.
* `<packaging>` - How the project should be packaged. Defaults to "jar" for JAR file packaging. Use "war" for WAR file packaging.

NOTE: When it comes to choosing a versioning scheme, Spring recommends the [semantic versioning](http://semver.org) approach.

At this point you have a minimal, yet capable Maven project defined.


== 构建Java代码
Maven is now ready to build the project. You can execute several build lifecycle goals with Maven now, including goals to compile the project's code, create a library package (such as a JAR file), and install the library in the local Maven dependency repository.

To try out the build, issue the following at the command line:

----
mvn compile
----

This will run Maven, telling it to execute the _compile_ goal. When it's finished, you should find the compiled _.class_ files in the _target/classes_ directory.

Since it's unlikely that you'll want to distribute or work with _.class_ files directly, you'll probably want to run the _package_ goal instead:

----
mvn package
----

The _package_ goal will compile your Java code, run any tests, and finish by packaging the code up in a JAR file within the _target_ directory. The name of the JAR file will be based on the project's `<artifactId>` and `<version>`. For example, given the minimal _pom.xml_ file from before, the JAR file will be named _{project_id}-0.1.0.jar_.

NOTE: If you've changed the value of `<packaging>` from "jar" to "war", the result will be a WAR file within the _target_ directory instead of a JAR file.

Maven also maintains a repository of dependencies on your local machine (usually in a _.m2/repository_ directory in your home directory) for quick access to project dependencies. If you'd like to install your project's JAR file to that local repository, then you should invoke the `install` goal:

----
mvn install
----

The _install_ goal will compile, test, and package your project's code and then copy it into the local dependency repository, ready for another project to reference it as a dependency.

Speaking of dependencies, now it's time to declare dependencies in the Maven build.

== 声明依赖
The simple Hello World sample is completely self-contained and does not depend on any additional libraries. Most applications, however, depend on external libraries to handle common and complex functionality.

For example, suppose that in addition to saying "Hello World!", you want the application to print the current date and time. While you could use the date and time facilities in the native Java libraries, you can make things more interesting by using the Joda Time libraries.

First, change HelloWorld.java to look like this:

`src/main/java/hello/HelloWorld.java`
[source,java]
----
include::complete/src/main/java/hello/HelloWorld.java[]
----

Here `HelloWorld` uses Joda Time's `LocalTime` class to get and print the current time.

If you were to run `mvn compile` to build the project now, the build would fail because you've not declared Joda Time as a compile dependency in the build. You can fix that by adding the following lines to _pom.xml_ (within the `<project>` element):

[source,xml,indent=0]
----
<dependencies>
include::complete/pom.xml[tag=joda]
</dependencies>
----

This block of XML declares a list of dependencies for the project. Specifically, it declares a single dependency for the Joda Time library. Within the `<dependency>` element, the dependency coordinates are defined by three sub-elements:

* `<groupId>` - The group or organization that the dependency belongs to.
* `<artifactId>` - The library that is required.
* `<version>` - The specific version of the library that is required.

By default, all dependencies are scoped as `compile` dependencies. That is, they should be available at compile-time (and if you were building a WAR file, including in the _/WEB-INF/libs_ folder of the WAR). Additionally, you may specify a `<scope>` element to specify one of the following scopes:

* `provided` - Dependencies that are required for compiling the project code, but that will be provided at runtime by a container running the code (e.g., the Java Servlet API).
* `test` - Dependencies that are used for compiling and running tests, but not required for building or running the project's runtime code.

Now if you run `mvn compile` or `mvn package`, Maven should resolve the Joda Time dependency from the Maven Central repository and the build will be successful.

== 写单元测试

First add JUnit as a dependency to your pom.xml, in the test scope:

[source,xml]
----
include::complete/pom.xml[tag=junit]
----

Then create a test case like this:

`src/test/java/hello/GreeterTest.java`
[source,java]
----
include::complete/src/test/java/hello/GreeterTest.java[]
----

Maven uses a plugin called "surefire" to run unit tests. The default configuration of this plugin compiles and runs all classes in `src/test/java` with a name matching `*Test`. You can run the tests on the command line like this

----
mvn test
----

or just use `mvn install` step as we already showed above (there is a lifecycle definition where "test" is included as a stage in "install").

Here's the completed `pom.xml` file:

`pom.xml`
[source,xml]
----
include::complete/pom.xml[]
----

NOTE: The completed **pom.xml** file is using the http://maven.apache.org/plugins/maven-shade-plugin/[Maven Shade Plugin]
for the simple convenience of making the JAR file executable. The focus of this guide is getting started with Maven,
not using this particular plugin.

== 总结
Congratulations! You've created a simple yet effective Maven project definition for building Java projects.

== 参考

The following guides may also be helpful:

* http://knos.top/guides/gs/gradle/[Building Java Projects with Gradle]

include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/footer.adoc[]
